import type { FoodItem, DeliveryLocation } from '@/lib/types';

export const menuItems: FoodItem[] = [
  {
    id: '1',
    name: 'Jollof Rice with Chicken',
    description: 'A classic West African dish featuring perfectly cooked rice in a rich tomato and pepper sauce, served with grilled chicken.',
    price: 3500,
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Main',
    'data-ai-hint': 'jollof rice',
  },
  {
    id: '2',
    name: 'Efo Riro',
    description: 'A rich Yoruba-style vegetable soup made with spinach, peppers, and assorted meats. A savory delight.',
    price: 4000,
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Soup',
    'data-ai-hint': 'vegetable soup',
  },
  {
    id: '3',
    name: 'Beef Suya Skewers',
    description: 'Spicy grilled beef skewers coated in a traditional peanut and spice blend. A popular Nigerian street food.',
    price: 2000,
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Sides',
    'data-ai-hint': 'grilled skewers',
  },
  {
    id: '4',
    name: 'Pounded Yam & Egusi',
    description: 'Soft, smooth pounded yam served with a hearty and flavorful egusi (melon seed) soup.',
    price: 4500,
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Soup',
    'data-ai-hint': 'yam soup',
  },
  {
    id: '5',
    name: 'Moi Moi',
    description: 'Steamed bean pudding made from a blend of washed and peeled black-eyed peas, onions, and fresh ground peppers.',
    price: 1000,
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Sides',
    'data-ai-hint': 'bean pudding',
  },
  {
    id: '6',
    name: 'Peppered Snails',
    description: 'Large, succulent snails sauteed in a spicy, flavorful pepper sauce. A true delicacy.',
    price: 5000,
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Sides',
    'data-ai-hint': 'spicy snails',
  },
  {
    id: '7',
    name: 'Abacha (African Salad)',
    description: 'A vibrant and tasty salad made from shredded cassava, vegetables, and a special dressing.',
    price: 2500,
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Main',
    'data-ai-hint': 'african salad',
  },
  {
    id: '8',
    name: 'Chapman Drink',
    description: 'A refreshing non-alcoholic mocktail, a staple at Nigerian parties. Sweet, fruity, and bubbly.',
    price: 1500,
    imageUrl: 'https://picsum.photos/600/400',
    category: 'Drinks',
    'data-ai-hint': 'red cocktail',
  },
];

export const deliveryLocations: DeliveryLocation[] = [
  { id: '1', name: 'Lekki Phase 1', price: 1500 },
  { id: '2', name: 'Victoria Island', price: 2000 },
  { id: '3', name: 'Ikoyi', price: 1800 },
  { id: '4', name: 'Ajah', price: 2500 },
];
